repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "" # Use the sha or tag you want to point at
      hooks:
          - id: prettier
    - repo: https://github.com/doublify/pre-commit-rust
      rev: master
      hooks:
          - id: fmt
          - id: cargo-check
