version: "3.9"
services:
    api:
        build:
            context: ./api
        ports: 
            - 8000:8000
    # nginx:
        # image: nginx:latest
    

    db:
        image: postgres:9.4
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=bad-password-manager-db

volumes:
    db-data: