version: "3.9"
services:
    api:
        build:
            context: ./api
        ports:
            - 8000:8000

    db:
        image: postgres:9.4
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=bad-password-manager-db

    nginx:
        build:
            context: ./app
        ports:
            - 80:80
volumes:
    db-data:
