[package]
name = 'bad_pass_manager_api'
version = '0.1.0'
edition = '2018'
authors = ['Kennan Hunter <kennanhunter5@gmail.com>']

[dependencies]
pbkdf2 = '0.8.0'
dotenv = "0.15.0"

[dependencies.diesel]
version = '1.4.4'
features = ['postgres']

[dependencies.rocket]
version = '0.4.10'
