name: bad-password-manager
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test-builds:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
            - name: Build api
              run: cargo +nightly build --release
              working-directory: ./api/
            - name: Run api tests
              run: cargo +nightly test --release
              working-directory: ./api/
    test-cli:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
            - name: Build cli
              run: cargo +nightly build --release
              working-directory: ./cli/
            - name: Run cli tests
              run: cargo +nightly test --release
              working-directory: ./cli/
    frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Install Dependencies
              run: npm install
              working-directory: ./app/
            - name: Build Frontend
              run: npm run build
              working-directory: ./app/
